In [1]:
import numpy as np
import matplotlib.pyplot as plt; plt.rcdefaults()
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

# fix_yahoo_finance is used to fetch data 
import yfinance as yf
yf.pdr_override()

In [ ]:
# input
symbol = 'TSLA'
start = '2000-01-15'
end = '2024-01-18'

# Read data 
dataset = yf.download(symbol,start,end)

# View Data
dataset.head()

In [ ]:
dataset.tail()

In [ ]:
plt.figure(figsize=(16,8))
plt.plot(dataset['Adj Close'])
plt.title('Closing Price Chart')
plt.xlabel('Date')
plt.ylabel('Price')
plt.grid(True)
plt.show()

In [ ]:
monthly = dataset.asfreq('BM')
monthly['Returns'] = dataset['Adj Close'].pct_change().dropna()
monthly.head()

In [ ]:
monthly['Month_Name'] = monthly.index.strftime("%b")
monthly['Month_Name_Year'] = monthly.index.strftime("%b-%Y")

In [ ]:
import calendar
import datetime

monthly = monthly.reset_index()
monthly['Month'] = monthly["Date"].dt.month

In [ ]:
monthly.head()

In [9]:
monthly.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Returns,Month_Name,Month_Name_Year,Month
0,2010-06-30,1.719333,2.028000,1.553333,1.588667,1.588667,257806500.0,-0.002511,Jun,Jun-2010,6
1,2010-07-30,1.346667,1.362667,1.303333,1.329333,1.329333,6403500.0,-0.020148,Jul,Jul-2010,7
2,2010-08-31,1.310667,1.319333,1.288667,1.298667,1.298667,3016500.0,-0.019628,Aug,Aug-2010,8
3,2010-09-30,1.466667,1.476667,1.346000,1.360667,1.360667,32937000.0,-0.071428,Sep,Sep-2010,9
4,2010-10-29,1.409333,1.456667,1.403333,1.456000,1.456000,4209000.0,0.030675,Oct,Oct-2010,10

In [10]:
monthly.tail()

,Date,Open,High,Low,Close,Adj Close,Volume,Returns,Month_Name,Month_Name_Year,Month
158,2023-08-31,255.979996,261.179993,255.050003,258.079987,258.079987,108861700.0,0.004593,Aug,Aug-2023,8
159,2023-09-29,250.000000,254.770004,246.350006,250.220001,250.220001,128346200.0,0.015586,Sep,Sep-2023,9
160,2023-10-31,196.119995,202.800003,194.070007,200.839996,200.839996,118068300.0,0.017633,Oct,Oct-2023,10
161,2023-11-30,245.139999,245.220001,236.910004,240.080002,240.080002,132353200.0,-0.016630,Nov,Nov-2023,11
162,2023-12-29,255.100006,255.190002,247.429993,248.479996,248.479996,100615300.0,-0.018564,Dec,Dec-2023,12

In [11]:
# input
symbol = 'AMZN'
start = '2000-01-15'
end = '2024-01-18'

# Read data 
dataset = yf.download(symbol,start,end)

# View Data
dataset.head(50)

[*********************100%%**********************]  1 of 1 completed

                Open      High       Low     Close  Adj Close     Volume
Date
2000-01-18  3.171875  3.259375  3.150000  3.206250   3.206250  107698000
2000-01-19  3.206250  3.375000  3.150000  3.340625   3.340625  164910000
2000-01-20  3.346875  3.350000  3.196875  3.237500   3.237500  119560000
2000-01-21  3.231250  3.231250  3.000000  3.103125   3.103125  229238000
2000-01-24  3.378125  3.668750  3.375000  3.506250   3.506250  583404000
2000-01-25  3.500000  3.562500  3.300000  3.462500   3.462500  188682000
2000-01-26  3.431250  3.500000  3.237500  3.240625   3.240625  131160000
2000-01-27  3.259375  3.387500  3.231250  3.346875   3.346875  135680000
2000-01-28  3.250000  3.321875  3.000000  3.084375   3.084375  275558000
2000-01-31  3.018750  3.237500  2.921875  3.228125   3.228125  213958000
2000-02-01  3.375000  3.531250  3.218750  3.371875   3.371875  268092000
2000-02-02  3.396875  3.612500  3.387500  3.471875   3.471875  280518000
2000-02-03  4.056250  4.296875  3.868750  4.209375   4.209375  875000000
2000-02-04  4.137500  4.137500  3.893750  3.928125   3.928125  220460000
2000-02-07  3.809375  3.843750  3.656250  3.750000   3.750000  202580000
2000-02-08  3.700000  4.200000  3.671875  4.156250   4.156250  389456000
2000-02-09  4.027344  4.186719  4.000781  4.012500   4.012500  191608000
2000-02-10  3.925000  3.993750  3.775000  3.809375   3.809375  199592000
2000-02-11  3.856250  3.956250  3.775000  3.809375   3.809375  166180000
2000-02-14  3.784375  3.787500  3.678125  3.721875   3.721875  103394000
2000-02-15  3.671875  3.809375  3.531250  3.690625   3.690625  128490000
2000-02-16  3.637500  3.671875  3.531250  3.534375   3.534375   85204000
2000-02-17  3.562500  3.565625  3.400000  3.450000   3.450000  122592000
2000-02-18  3.421875  3.450000  3.193750  3.237500   3.237500  174528000
2000-02-22  3.246875  3.325000  3.153125  3.178125   3.178125  113716000
2000-02-23  3.243750  3.587500  3.234375  3.521875   3.521875  168824000
2000-02-24  3.528125  3.568750  3.281250  3.421875   3.421875  117386000
2000-02-25  3.371875  3.468750  3.259375  3.456250   3.456250   97410000
2000-02-28  3.328125  3.359375  3.206250  3.287500   3.287500  101154000
2000-02-29  3.300000  3.448438  3.293750  3.443750   3.443750  142970000
2000-03-01  3.381250  3.425000  3.250000  3.293750   3.293750  111534000
2000-03-02  3.246875  3.250000  3.109375  3.128125   3.128125  159602000
2000-03-03  3.162500  3.237500  3.103125  3.125000   3.125000  121190000
2000-03-06  3.143750  3.362500  3.140625  3.196875   3.196875  153316000
2000-03-07  3.243750  3.290625  3.106250  3.175000   3.175000   83576000
2000-03-08  3.162500  3.237500  3.028125  3.181250   3.181250  118814000
2000-03-09  3.150000  3.450000  3.109375  3.440625   3.440625  166250000
2000-03-10  3.362500  3.426563  3.250000  3.343750   3.343750   74270000
2000-03-13  3.200000  3.331250  3.150000  3.265625   3.265625  112686000
2000-03-14  3.303125  3.346875  3.168750  3.281250   3.281250   96106000
2000-03-15  3.237500  3.256250  3.100000  3.187500   3.187500  121654000
2000-03-16  3.112500  3.318750  3.000000  3.312500   3.312500  194062000
2000-03-17  3.303125  3.318750  3.225000  3.240625   3.240625  105970000
2000-03-20  3.175000  3.225000  3.118750  3.209375   3.209375  116270000
2000-03-21  3.256250  3.650000  3.112500  3.618750   3.618750  341658000
2000-03-22  3.543750  3.700000  3.462500  3.534375   3.534375  231328000
2000-03-23  3.475000  3.546875  3.375000  3.384375   3.384375  108842000
2000-03-24  3.731250  3.762500  3.565625  3.634375   3.634375  194920000
2000-03-27  3.612500  3.756250  3.587500  3.656250   3.656250   94972000
2000-03-28  3.618750  3.637500  3.473438  3.506250   3.506250  103952000

In [12]:
pip install nb2xls

Requirement already satisfied: nb2xls in c:\users\chris\anaconda3\lib\site-packages (0.1.6)
Requirement already satisfied: beautifulsoup4>=4.6.0 in c:\users\chris\anaconda3\lib\site-packages (from nb2xls) (4.11.1)
Requirement already satisfied: xlsxwriter>=1.1.0 in c:\users\chris\anaconda3\lib\site-packages (from nb2xls) (3.0.3)
Requirement already satisfied: pypng>=0.0.18 in c:\users\chris\anaconda3\lib\site-packages (from nb2xls) (0.20220715.0)
Requirement already satisfied: numpy in c:\users\chris\anaconda3\lib\site-packages (from nb2xls) (1.21.5)
Requirement already satisfied: mistune>=0.8 in c:\users\chris\anaconda3\lib\site-packages (from nb2xls) (0.8.4)
Requirement already satisfied: nbconvert>=5.0.0 in c:\users\chris\anaconda3\lib\site-packages (from nb2xls) (6.4.4)
Requirement already satisfied: pandas in c:\users\chris\anaconda3\lib\site-packages (from nb2xls) (1.4.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\chris\anaconda3\lib\site-packages (from beautifulsoup4>=4.6.0->nb2xls) (2.3.1)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (0.4)
Requirement already satisfied: jupyterlab-pygments in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (0.1.2)
Requirement already satisfied: bleach in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (4.1.0)
Requirement already satisfied: jupyter-core in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (4.11.1)
Requirement already satisfied: jinja2>=2.4 in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (2.11.3)
Requirement already satisfied: nbformat>=4.4 in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (5.5.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (0.5.13)
Requirement already satisfied: pygments>=2.4.1 in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (2.11.2)
Requirement already satisfied: defusedxml in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (0.7.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (1.5.0)
Requirement already satisfied: testpath in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (0.6.0)
Requirement already satisfied: traitlets>=5.0 in c:\users\chris\anaconda3\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (5.1.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\chris\anaconda3\lib\site-packages (from pandas->nb2xls) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\chris\anaconda3\lib\site-packages (from pandas->nb2xls) (2.8.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\chris\anaconda3\lib\site-packages (from jinja2>=2.4->nbconvert>=5.0.0->nb2xls) (2.0.1)
Requirement already satisfied: jupyter-client>=6.1.5 in c:\users\chris\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=5.0.0->nb2xls) (7.3.4)
Requirement already satisfied: nest-asyncio in c:\users\chris\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=5.0.0->nb2xls) (1.5.5)
Requirement already satisfied: fastjsonschema in c:\users\chris\anaconda3\lib\site-packages (from nbformat>=4.4->nbconvert>=5.0.0->nb2xls) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\chris\anaconda3\lib\site-packages (from nbformat>=4.4->nbconvert>=5.0.0->nb2xls) (4.16.0)
Requirement already satisfied: six>=1.5 in c:\users\chris\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas->nb2xls) (1.16.0)
Requirement already satisfied: webencodings in c:\users\chris\anaconda3\lib\site-packages (from bleach->nbconvert>=5.0.0->nb2xls) (0.5.1)
Requirement already satisfied: packaging in c:\users\chris\anaconda3\lib\site-packages (from bleach->nbconvert>=5.0.0->nb2xls) (21.3)
Requirement already satisfied: pywin32>=1.0 in c:\users\chris\anaconda3\lib\site-packages (from jupyter-core->nbconvert>=5.0.0->nb2xls) (302)
Requirement already satisfied: attrs>=17.4.0 in c:\users\chris\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.4->nbconvert>=5.0.0->nb2xls) (21.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\chris\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.4->nbconvert>=5.0.0->nb2xls) (0.18.0)
Requirement already satisfied: tornado>=6.0 in c:\users\chris\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient<0.6.0,>=0.5.0->nbconvert>=5.0.0->nb2xls) (6.1)
Requirement already satisfied: pyzmq>=23.0 in c:\users\chris\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient<0.6.0,>=0.5.0->nbconvert>=5.0.0->nb2xls) (23.2.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\chris\anaconda3\lib\site-packages (from packaging->bleach->nbconvert>=5.0.0->nb2xls) (3.0.9)
Note: you may need to restart the kernel to use updated packages.

In [32]:
# input
symbol = 'FVRR'
start = '2000-01-15'
end = '2024-01-18'

# Read data 
dataset = yf.download(symbol,start,end)

# View Data
dataset.head()

[*********************100%%**********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close    Volume
Date
2019-06-13  26.000000  41.680000  25.549999  39.900002  39.900002  22046000
2019-06-14  41.639999  44.250000  31.490000  31.490000  31.490000  10275800
2019-06-17  32.810001  34.880001  31.541000  34.380001  34.380001   3789100
2019-06-18  35.259998  35.919998  31.040001  31.150000  31.150000   3274000
2019-06-19  31.799999  31.799999  28.250000  28.670000  28.670000   1902000